services:
  app:
    # build: .
    # ports:
    #   - 4000:3000
    # volumes:
    #   - type: bind
    #     source: .
    #     target: /home/src/app
    # env_file:
    #   - .env.local
    # command: npm run dev
    image: node:20-alpine
    command: sh -c "npm install && npm run dev"
    ports:
      - 127.0.0.1:4000:3000
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - .env.local